### ISSUE TITLE
有无机器学习和高级算法分析设计的课件，bro

### ISSUE THREAD

**Issue by happyfox-dot** [onford/hust-notes#1]

**Comment by onford** [comment]
没有诶哥们，我机器学习的课没选，然后我们好像没开高级算法分析设计这门课？

**Comment by happyfox-dot** [comment]
好吧，谢谢哥了。如果方便的话，能不能能帮忙找份机器学习的课件 :heart:

**Comment by onford** [comment]
> 好吧，谢谢哥了。如果方便的话，能不能能帮忙找份机器学习的课件 ❤️

@happyfox-dot  课件倒是没找到，github上还是有一些笔记的，比如[这个](https://github.com/AlexFanw/HUSTER-CS/tree/master/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0)，sukuna学长的[仓库](https://github.com/SukunaShinmyoumaru-hust/Hust-opensource-Xuejie)也比较推荐。
